version: '3'

services:
    node:
        container_name: almoxarifado-api
        build: .
        volumes:
            - .:/app
            - ./node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=8080
            - MYSQL_CONNECTION_URL=mysql://almoxarifado_root:90e271d9b4ae4a6812e86cee@almoxarifado-mysql:3306
        networks:
            - almoxarifado-connect
        links:
            - mysql
        ports:
            - 4444:8080

    mysql:
        container_name: almoxarifado-mysql
        restart: always
        image: mysql:5.7
        volumes:
            - ~/docker/volumes/ALMOXARIFADO_Mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: almoxarifado-database
            MYSQL_USER: almoxarifado_root
            MYSQL_PASSWORD: 90e271d9b4ae4a6812e86cee
            MYSQL_ROOT_PASSWORD: 327c56a1d1c5803d92a4dad9
        networks:
            - almoxarifado-connect
        ports:
            - 3306:3306

volumes:
    almoxarifado-node-data:
    almoxarifado-mysql-data:

networks:
    almoxarifado-connect:
        driver: bridge
